### ISSUE TITLE
Title Screen Rearrangement

### ISSUE THREAD

**Issue by SkynetCyberdyne** [VoltzModpack/Voltz#12]
Since there are many people that have problems with, this, that, and the other thing. And no one even bothers to look at the title screen closely, my suggestion is that right underneath the Single/Multiplayer buttons, the Issue button is clearly represented. Same thing with the discord and other buttons.

**Comment by kmecpp** [comment]
I don't think changing their position on the title screen would have much effect on people reporting issues correctly. There's also the matter that I cannot put the server issue tracker on the main menu which would probably lead to many players wrongly reporting server issues on the modpack page.
