### ISSUE TITLE
Making a server

### ISSUE THREAD

**Issue by umbemeh** [VoltzModpack/Voltz#22]
When I try to join my own server it says "Lost connection Mod rejections" and then lists some mods
Does anyone know how to fix this?

**Comment by kmecpp** [comment]
Screenshot the mod rejections.

Taking the server mods you have on your client (everything but DynamicsLights, ResourceLoader and CustomMainMenu) should solve your problem

**Comment by umbemeh** [comment]
![image](https://user-images.githubusercontent.com/46875088/51453643-37854180-1d06-11e9-805a-4a3125aac448.png)

**Comment by umbemeh** [comment]
![image](https://user-images.githubusercontent.com/46875088/51453662-51268900-1d06-11e9-9c74-2365bf79a2e3.png)

This is what keeps poping up

**Comment by umbemeh** [comment]
![image](https://user-images.githubusercontent.com/46875088/51453676-6c919400-1d06-11e9-9ce6-94389a0bcc87.png)

this is what keeps poping up

**Comment by kmecpp** [comment]
Take those mods from your client (in %appdata%\.technic\modpacks\volts-community-modpack\mods)

and put them in the server
