### ISSUE TITLE
Golden Shovel Claiming 

### ISSUE THREAD

**Issue by H3LLSANGEL** [VoltzModpack/Voltz#30]
So I would like to propose possibly switching to a golden shovel claiming system rather than factions. Right now factions is barely being used as players are gathering the understanding that claiming is detrimental to your base. With that, players can either claim there base and be easier to find or not claim it and have no protection at all if someone finds it(Minus turrets). So right now there is not really a true raiding scene. Golden shovel claiming would allow new players to be able to provide at least some form of protection without it giving away your position. I understand once MFFS comes back into play it may not be as important but I still think it would be more beneficial to everyone but especially new players. Then this would allow a raiding scene rather than just finding and breaking everything. What do you all think?

**Comment by H3LLSANGEL** [comment]
Also will add:

I don't think there is currently anyway to add the crafting addon to the wireless universal terminal. Would be nice to have wireless AE crafting.

**Comment by kmecpp** [comment]
This issue tracker is only for modpack issues
