### ISSUE TITLE
Metallurgic Infuser destroying diamond dust

### ISSUE THREAD

**Issue by Plextanium** [VoltzModpack/Voltz#32]
I was producing Refined Obsidian Dust in a basic Metallurgic Infuser. One had completed production already, another one in the process. I had 1 item of Diamond Dust 4887 (10 units) stored to do so. The progress bar reached about 40% and then suddenly stopped. The dust was out of the machine, gone. This happened about the same time that the server saved. I'm not sure why it was gone.

**Comment by kmecpp** [comment]
Should be fixed now
