### ISSUE TITLE
Ticking Entity Error prevents login to official server

### ISSUE THREAD

**Issue by ClownJesterKing** [VoltzModpack/Voltz#33]
A few of us were trying to figure out how to power our redstone furnace and pulverizer. We attached a steam dynamo to them and made a blast furnace as well. We then received several errors regarding ticking entity errors. I probably tried logging in a dozen times and it gave me the same error. 

[crash-2019-07-04_15.04.44-client.txt](https://github.com/VoltzModpack/Voltz/files/3360385/crash-2019-07-04_15.04.44-client.txt)

The error report is pasted here and i'm sure I can't fix it due to it being part of the official server. If I need to provide coordinates, I can give a rough estimation of where it is I received the issue.

**Comment by kmecpp** [comment]
Update to the latest version of the modpack
