### ISSUE TITLE
I cant join the server

### ISSUE THREAD

**Issue by StivHD** [VoltzModpack/Voltz#36]
When i try to connect to the server it starts to login but then i get a messege:Failed to login:Invalid session(you logged into MC somewhere else)
Login again using the button in the top left corner of the multyplayer menu or restart your launcher. 
So i did i tried to login but it says: Invalid credentials.Invalid username or password.

**Comment by kmecpp** [comment]
Then you typed in your credentials wrong. Restarting your game and game launcher will def fix it
