### ISSUE TITLE
Energetic infuser / Atomic dis glitch

### ISSUE THREAD

**Issue by Quigybobo** [VoltzModpack/Voltz#38]
When you put an atomic dis in a energetic infuser to charge, once at full capacity and switches inventory sides, it goes poof! I've test 3 times. All 3 disapeared.

**Comment by kmecpp** [comment]
Unable to replicate this

**Comment by Quigybobo** [comment]
Something at the base was making it disapear. This issue was player created I figured out by another player on server. Not bug related. Issue was resolved.
