### ISSUE TITLE
Voting rewards not working

### ISSUE THREAD

**Issue by Quigybobo** [VoltzModpack/Voltz#39]
Voting rewards on the PVE S3 server are not working correctly. When a player votes they are issued papers that can be used to get rewards sometimes. These papers do not work. Some players have 10k in cash papers, where some have basic keys. Crates are confirmed to be working with keys directly, but the actual papers do not work / work on crates for exchange.

**Comment by kmecpp** [comment]
This is the issue tracker for modpack issues. For server issues go here: [http://bugs.voidflame.com](http://bugs.voidflame.com)
