### ISSUE TITLE
Digital Miner Bug

### ISSUE THREAD

**Issue by virtrum** [VoltzModpack/Voltz#40]
The Digital Miner's interface includes the option to control its activation via a redstone signal, but this doesn't appear to be working currently. According to https://ftb.gamepedia.com/Digital_Miner:

"Redstone tab: Toggles when the Digital Miner will function; High makes it run when a redstone signal is present, Low makes it run when any redstone signal is absent, and Disabled will have it run independent of the presence or absence of redstone signals."

None of these settings seem to make a difference with the miner. Tested with every redstone source I could think of, including covering the miner in redstone blocks.

**Comment by kmecpp** [comment]
Can't replicate this issue. Are you still giving it power? What environment are you testing it on?

**Comment by virtrum** [comment]
Retested, this time targeting ore. Looks like the redstone signal only controls if the miner is paused or not, assuming the miner is already started. I had thought that the redstone signal would control Start/Stop functionality, but that doesn't appear to be the case. Only pauses if the miner is already started. If that's intended, feel free to close this.

-- Side note, if the above is intended, is there any way to control start/stop outside of the miner's GUI?

**Comment by kmecpp** [comment]
Pretty sure that's the intended behavior. I can probably change it if you have a good reason for needing it the other way?

**Comment by virtrum** [comment]
I had planned to use miners as a defense system of sorts, for detecting and removing "malicious" blocks based on a redstone pulse, but that would only work if the miners interacted with redstone the way I had originally thought they did. Up to you if you want to change it, but it would make for some interesting automation capabilities around miners.

**Comment by kmecpp** [comment]
Probably better to use something like the interdiction matrix for that as that's its intended purpose

You should be able to get it to emit a red stone signal if someone in its range tries to alter a block without access
