### ISSUE TITLE
Lack of Rocket Schematics Prevents Galacticraft Progression - Voltz Community Modpack Server

### ISSUE THREAD

**Issue by Savill00** [VoltzModpack/Voltz#61]
Limited Dungeons on other planets due to world limits means that all accessible dungeons are looted already. Since this is the only way to get rocket schematics it's very difficult to progress to higher tier planets, limiting the players ability to enjoy the mod's fill potential.
Possible fix could be to make a public use NASA workbench with all schematics pre-added, or perhaps add schematics to server store.

**Comment by kmecpp** [comment]
Wrong issue tracker
