### ISSUE TITLE
Client crashes on server connect

### ISSUE THREAD

**Issue by DicksAnonymous** [VoltzModpack/Voltz#9]
For about a month I have been trying to connect and play on the Official server after experiencing a random crash while building a Boiler. I can connect to the server but as soon as the HUD appears my client crashes. I have no clue whats making me crash every time.

**Comment by kmecpp** [comment]
Crash report?

**Comment by DicksAnonymous** [comment]
[Crash report.txt](https://github.com/VoltzModpack/Voltz/files/2343664/Crash.report.txt)

**Comment by kmecpp** [comment]
Can you contact me on Discord so I can create a permanent patch for this bug: https://discord.gg/G7rYe49
